Importing the Dependencies

In [4]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [7]:
#printing the stopwords
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

Data Pre-Processing

In [10]:
#load the data to a pandas dataframe
news_data = pd.read_csv('/content/fake_news_dataset.csv', encoding='latin1', on_bad_lines='skip')

In [11]:
news_data.head()

  id  ... label
0  0  ...     1
1  1  ...     0
2  2  ...     1
3  3  ...     1
4  4  ...     1

[5 rows x 5 columns]

0--> Real News
1--> Fake news

In [12]:
news_data.shape

(39455, 5)

In [13]:
#checking the missing values
news_data.isnull().sum()

id           0
title     1065
author    3700
text        98
label       36
dtype: int64

In [14]:
#replacing the missing values with null string
news_data = news_data.fillna('tree')

In [15]:
#merging the author name and news title
news_data['content']= news_data['author']+' '+news_data['title']

In [16]:
news_data.head()

  id  ...                                            content
0  0  ...  Darrell Lucus House Dem Aide: We Didnât Even...
1  1  ...  Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2  2  ...  Consortiumnews.com Why the Truth Might Get You...
3  3  ...  Jessica Purkiss 15 Civilians Killed In Single ...
4  4  ...  Howard Portnoy Iranian woman jailed for fictio...

[5 rows x 6 columns]

In [19]:
#seperating Feature and Target
X = news_data.drop(columns='label', axis=1)
Y = news_data['label']

Stemming:

Stemming is the process of reducing a word to its rootword

In [20]:
port_stem = PorterStemmer()

In [25]:
def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]',' ',content)
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  return ' '.join(stemmed_content)

In [26]:
news_data['content']= news_data['content'].apply(stemming)

In [27]:
print(news_data['content'])

0        darrel lucu hous dem aid even see comey letter...
1        daniel j flynn flynn hillari clinton big woman...
2                   consortiumnew com truth might get fire
3        jessica purkiss civilian kill singl us airstri...
4        howard portnoy iranian woman jail fiction unpu...
                               ...
39450    jerom hudson rapper trump poster child white s...
39451    benjamin hoffman n f l playoff schedul matchup...
39452    michael j de la merc rachel abram maci said re...
39453    alex ansari nato russia hold parallel exercis ...
39454                            david swanson keep f aliv
Name: content, Length: 39455, dtype: object

In [29]:
X = news_data['content'].values
Y = news_data['label'].values

In [30]:
print(X)

['darrel lucu hous dem aid even see comey letter jason chaffetz tweet'
 'daniel j flynn flynn hillari clinton big woman campu breitbart'
 'consortiumnew com truth might get fire' ...
 'michael j de la merc rachel abram maci said receiv takeov approach hudson bay new york time'
 'alex ansari nato russia hold parallel exercis balkan'
 'david swanson keep f aliv']

In [31]:
print(Y)

['1' '0' '1' ... '0' '1' '1']

In [33]:
Y.shape

(39455,)

In [34]:
#converting the textual data to feature vector
vectorizer = TfidfVectorizer()
vectorizer.fit(X)

TfidfVectorizer()

In [35]:
X= vectorizer.transform(X)