Imbalanced Dataset:

A dataset with an unequal class distribution

In [1]:
# importing the dependencies
import numpy as np
import pandas as pd

In [9]:
#loading the dataset to pandas DataFrame
credit_card_data = pd.read_csv('/content/credit_data.csv', on_bad_lines='skip')

/tmp/ipython-input-1652766655.py:2: DtypeWarning: Columns (0,1,2,4,7,8,10,11,13,15,17,20,22,24) have mixed types. Specify dtype option on import or set low_memory=False.
  credit_card_data = pd.read_csv('/content/credit_data.csv', on_bad_lines='skip')

In [10]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.37978,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [11]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
563506,172786,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0.0
563507,172787,-0.732789,-0.05508,2.035030,-0.738589,0.868229,1.058415,0.02433,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0.0
563508,172788,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0.0
563509,172788,-0.24044,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.68618,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0.0
563510,172792,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.41465,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0.0

In [12]:
# distribution of two classes
credit_card_data['Class'].value_counts()

Class
0.0    562393
1.0       981
Name: count, dtype: int64

This is Highly imbalanced Dataset

0--> Legit Transactions
1--> Fraudulent Transactions

In [15]:
#Seperating the legit and fraudulent transactions
legit = credit_card_data[credit_card_data.Class== 0]
fraud = credit_card_data[credit_card_data.Class== 1]

In [16]:
print(legit.shape)
print(fraud.shape)

(562393, 31)
(981, 31)

Under-Sampling

Build a sample dataset containing similar distribution of Legit & Fraudulent Transactions.

Number of Fraudulent Transactions-->492

In [17]:
legit_sample = legit.sample(n=492)

In [18]:
print(legit_sample.shape)

(492, 31)

Concatenate the Two DataFrames

In [19]:
new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [20]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
445494,146016.0,-0.317385,0.995270021342058,-0.668552,-0.652759,1.557943,-0.679072,1.645444,-1.073268,1.501391,...,-0.060672,0.788166,-0.320807,-1.180955,-0.257754,-0.204977,-0.492097,-0.509742,6.91,0.0
125300,50032,1.096441,0.247292,1.449417,2.652978,-0.773799,0.046267,-0.483269,0.126451,-0.045989,...,-0.033605,-0.050347,0.033304,0.383234,0.263300,-0.051038,0.034167,0.039962,20.42,0.0
253179,78004,1.312436,0.65836,-0.771562,0.754528,0.372393,-1.168207,0.41415,-0.29802,-0.164349,...,-0.184335,-0.460669,-0.147523,-0.220877893542315,0.644321,0.399148,-0.029983,0.038262,0.76,0.0
549663,166106.0,-1.703155,2.32209,-2.286065,-1.297274,0.255505,-1.404406,0.488041,0.997858,-0.520651,...,0.300783,0.830863,-0.120318,-0.460749,-0.058806,0.119952,0.327931,0.246791,1.46,0.0
356067,123356,-0.105138,1.232222,-0.785641,1.123375,0.734731,-0.961177,1.01867,0.04113,-0.803048,...,0.291809,0.938823,-0.020548,-0.055105,-0.790606,-0.533564,0.179543,0.195400,17.43,0.0

In [21]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
558567,169142,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.88285,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1.0
558847,169347,1.378559,1.289381,-5.004247,1.41185,0.442581,-1.326536,-1.41317,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1.0
558853,169351,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.03207,-0.739695,0.471111,0.385107,0.194361,77.89,1.0
559848,169966,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1.0
560378,170348,1.991976,0.158476,-2.583441,0.40867,1.151147,-0.096695,0.22305,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1.0

In [23]:
new_dataset['Class'].value_counts()

Class
1.0    981
0.0    492
Name: count, dtype: int64